/* Noventa Gradox: all interaction settings live here. */
(() => {
  const CONFIG = { whatsapp: '573002573965', youtubeId: 'ffFSh73KrFo' };
  const whatsapp = message => `https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(message)}`;
  const projects = [['boda-01.jpg','Bodas','Atardecer para dos','bodas'],['evento-02.jpg','Eventos','Una noche que vibra','eventos'],['retrato-01.jpg','Retratos','Luz propia','retratos'],['producto-01.jpg','Productos','Materia y deseo','productos'],['gastronomia-01.jpg','Gastronomía','Sabor en detalle','gastronomia'],['corporativo-01.jpg','Corporativo','Presencia que conecta','corporativo'],['estudio-02.jpg','Estudio','Dirección de luz','estudio'],['contenido-01.jpg','Contenido para redes','La marca en movimiento','redes']];
  const $ = (selector, parent=document) => parent.querySelector(selector); const $$ = (selector, parent=document) => [...parent.querySelectorAll(selector)];
  $('#quote-float').href = whatsapp('QUIERO COTIZAR MI EVENTO'); $('#contact-whatsapp').href = whatsapp('Hola, quiero información sobre los servicios de Noventa Gradox.');
  $$('.service').forEach(card => { const title = $('h3', card).textContent; card.tabIndex=0; card.setAttribute('role','link'); const go=()=>window.open(whatsapp(`Estoy interesado en el servicio de ${title}. Vengo desde la web oficial.`),'_blank','noopener'); card.onclick=go; card.onkeydown=e=>{if(e.key==='Enter')go();}; });
  const grid=$('#portfolio-grid'), box=$('#lightbox'); let current=0;
  const draw=filter=>{const list=projects.filter(p=>filter==='all'||p[3]===filter);grid.innerHTML=list.map(p=>`<button class="project-card" data-project="${projects.indexOf(p)}"><img src="images/portfolio/${p[0]}" alt="${p[1]}: ${p[2]}" loading="lazy"><span><small>${p[1]}</small><b>${p[2]}</b></span></button>`).join('');};
  const paint=()=>{const p=projects[current],img=$('img',box);img.src=`images/portfolio/${p[0]}`;img.alt=`${p[1]}: ${p[2]}`;$('figcaption span',box).textContent=p[1];$('figcaption strong',box).textContent=p[2];$('figcaption small',box).textContent=`${current+1} / ${projects.length}`;};
  const openBox=i=>{current=i;paint();box.classList.add('open');box.setAttribute('aria-hidden','false');document.body.classList.add('locked');}; const closeBox=()=>{box.classList.remove('open');box.setAttribute('aria-hidden','true');document.body.classList.remove('locked');}; draw('all');
  grid.onclick=e=>{const card=e.target.closest('[data-project]');if(card)openBox(+card.dataset.project);}; $$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('is-selected'));b.classList.add('is-selected');draw(b.dataset.filter);}); $('.modal-prev',box).onclick=()=>{current=(current+projects.length-1)%projects.length;paint();};$('.modal-next',box).onclick=()=>{current=(current+1)%projects.length;paint();};$('[data-close="lightbox"]').onclick=closeBox;box.onclick=e=>{if(e.target===box)closeBox();};
  const video=$('#video-modal'), frame=$('.video-frame',video),closeVideo=()=>{video.classList.remove('open');video.setAttribute('aria-hidden','true');frame.innerHTML='';document.body.classList.remove('locked');}; $('#play-video').onclick=()=>{frame.innerHTML='<video src="videos/showreel.mp4" controls autoplay muted playsinline aria-label="Video de Noventa Gradox"></video>';video.classList.add('open');video.setAttribute('aria-hidden','false');document.body.classList.add('locked');};$('[data-close="video"]').onclick=closeVideo;video.onclick=e=>{if(e.target===video)closeVideo();};
  addEventListener('keydown',e=>{if(e.key==='Escape'){closeBox();closeVideo();}if(box.classList.contains('open')&&e.key==='ArrowLeft')$('.modal-prev',box).click();if(box.classList.contains('open')&&e.key==='ArrowRight')$('.modal-next',box).click();});
  const nav=$('#main-nav'),toggle=$('.menu-toggle');toggle.onclick=()=>{const open=nav.classList.toggle('open');toggle.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));};$$('.nav a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');toggle.classList.remove('open');toggle.setAttribute('aria-expanded','false');});
  const heroSlides=$$('.hero-media'),heroDots=$$('.hero-slider button');let heroCurrent=0;const changeHero=index=>{heroCurrent=(index+heroSlides.length)%heroSlides.length;heroSlides.forEach((slide,i)=>slide.classList.toggle('active',i===heroCurrent));heroDots.forEach((dot,i)=>dot.classList.toggle('active',i===heroCurrent));};heroDots.forEach((dot,index)=>dot.onclick=()=>changeHero(index));setInterval(()=>changeHero(heroCurrent+1),6500);
  const top=$('.back-to-top'),header=$('.header'),progress=$('.progress span');addEventListener('scroll',()=>{const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;header.classList.toggle('scrolled',y>40);top.classList.toggle('visible',y>700);progress.style.width=`${max?y/max*100:0}%`;},{passive:true});top.onclick=()=>scrollTo({top:0,behavior:'smooth'});
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.14});$$('.reveal').forEach(item=>observer.observe(item));
  $('#contact-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);const message=`Consulta web\n\nNombre: ${d.get('name')}\nTeléfono: ${d.get('phone')}\nServicio: ${d.get('service')}\nFecha: ${d.get('date')||'Por definir'}\nMensaje: ${d.get('message')}`;window.open(whatsapp(message),'_blank','noopener');$('.form-status').textContent='Abriendo WhatsApp para enviar tu consulta.';};
})();
